### Get data by id
GET http://localhost:8082/reactive/data/1

### Call delay endpoint at legacy backend
GET http://localhost:8082/reactive/delay/8000
Accept: application/json

### Call delay endpoint at legacy backend. This will take too long and break the circuit.
GET http://localhost:8082/reactive/delay/22000
Accept: application/json

### Delay 666 results in BadRequest
GET http://localhost:8082/reactive/delay/666
Accept: application/json